src/styles/grid/index.css
Add style to the new prop called `fullHeight` on former-kit.
=> landing: add full-height style

src/styles/table/index.css
Add disable class for table and it's children. This class only change the cursor to `not-allowed` and the user selection to `none`
Closes #32
=> Add table disabled class

src/styles/grid/index.css
ref: https://github.com/pagarme/former-kit/pull/46
=> grid-alignemnt: add new alignment options

package.json, src/styles/header/header-back-button.css, src/styles/legend/index.css, src/styles/pagination/index.css, src/styles/sidebar/sidebar-link.css, src/styles/table/index.css
This fixes a globbing error in linter scripts, which caused linter to
always pass. This PR fixes both addresses the linting issues and fixes
the script glob.
=> Fix linter script

.circleci/config.yml, src/styles/table/body.css, src/styles/table/footer.css, src/styles/table/index.css, src/styles/table/properties.css
Add a footer row for columns agregations
=> Add table aggregation row

src/styles/card/CardSection.css, src/styles/card/index.css, src/styles/card/properties.css
This refactors CardSection to split the two title variants in separate components.
=> Refactor card section title variants

src/styles/segmented-switch/index.css, src/styles/segmented-switch/properties.css
A versão dark não será utilizada por enquanto, alterei para a versão light.
=> segmented-switch: refactor style

src/styles/table/body.css, src/styles/table/expandableRow.css, src/styles/table/head.css, src/styles/table/index.css, src/styles/table/properties.css, src/styles/table/row.css
Organização de CSS e ajustes na classe `empty`.
=> table: refactor style

src/styles/card/CardSection.css
Add var with a correct color in CardSection title
=> cardSection add color var

src/styles/modal/index.css, src/styles/modal/properties.css
Refactor modal spacings and title
=> Modal refactoring

src/styles/steps/index.css, src/styles/steps/properties.css
Related to https://github.com/pagarme/former-kit/pull/115
=> steps: remove background color and add error

src/styles/layout/index.css, src/styles/modal/index.css
reseta os estilos do elemento `fieldset` removendo as bordas e adicionando herança no propriedade `display`
=> fieldset: reset element style

src/styles/card/CardSection.css, src/styles/card/index.css, src/styles/card/properties.css
Refatoração de tamanho de fonte, peso, cores, etc dos títulos.
=> card: refactor titles

src/styles/header/header-title.css, src/styles/header/index.css, src/styles/header/properties.css
- Refactor back-button color and margin
- Change box-shadow to border.
=> Header + back button design improvements

package.json
=> release: bump version to 0.5.1

src/styles/modal/index.css, src/styles/modal/properties.css
https://github.com/pagarme/former-kit/pull/129
=> modal: add section style

package.json
=> Release version to 0.5.2

src/styles/pagination/index.css, src/styles/pagination/properties.css
- Add tiny size style
https://github.com/pagarme/former-kit/pull/137
=> pagination: add size styles

src/styles/dropdown/index.css, src/styles/dropdown/properties.css
- Add tiny size style
https://github.com/pagarme/former-kit/pull/138
=> dropdown: add size styles

src/styles/index.js, src/styles/spacing/index.css
- Add spacing component styles
https://github.com/pagarme/former-kit/pull/140
=> spacing: add styles

src/styles/card/CardSection.css, src/styles/card/properties.css
Add actions options and refactor click area in card section double line title component
https://github.com/pagarme/former-kit/pull/116
=> card-section-double-line-title: refactor component

src/styles/form-fields/input/index.css
Add `width: 100%` to input style
=> input: update width

src/styles/spacing/index.css
- Add reset margin to the component and its sibling.
=> spacing: reset margin

package.json
=> release: bump version to 0.6.0

src/icons/calendar/index.js, src/icons/index.js, src/styles/react-dates/index.css
Add calendar icons and styles.
This component will use the `ReactDates-overrides` like the `DateSelector`. 
In future will use the `DateSelector` will use `Calendar` component as child.
=> Add calendar

src/styles/grid/index.css
This PR fix alignment on `Col` component update from `justify-content` to `align-items`
resolve pagarme/former-kit#149
=> grid-col: update justify to align

package.json
Updates version to release the v0.7.0 version
=> release: bump version to 0.7.0

package.json
=> release: bump version to 0.8.0

src/styles/segmented-switch/index.css, src/styles/segmented-switch/properties.css
=> Segmented-switch add disabled style

src/styles/popover/index.css, src/styles/popover/properties.css
=> popover: fix link font-size

src/styles/tooltip/index.css, src/styles/tooltip/properties.css
- Fix text font-size, font-weight, line-height e text-transform
- Sort variables
=> tooltip: fix text style

package.json
=> release: bump version to 0.8.1

src/styles/table/index.css
Fix table removing table item overflow hidden
=> Fix table item overflow hidden

src/styles/form-fields/dropdown/index.css, src/styles/form-fields/dropdown/properties.css
=> dropdown: remove background-color

src/styles/bullet-steps/index.css, src/styles/bullet-steps/properties.css, src/styles/index.js
Add a new component, `bullet-step` (logic at https://github.com/pagarme/former-kit/pull/183)
closes https://github.com/pagarme/pilot/issues/861
=> bullet-step: add component

src/styles/index.js, src/styles/segmented-switch/properties.css, src/styles/segmented-switch/spaced/index.css
Skin for a new component, `spaced-segmented-switch` (PR https://github.com/pagarme/former-kit/pull/182).
closes https://github.com/pagarme/pilot/issues/798
=> spaced-segmented-switch: add component

package.json
=> release: bump version to 0.9.0

src/styles/popover/index.css, src/styles/popover/properties.css
Refactor popover content title color and spacements menu options
https://github.com/pagarme/former-kit-skin-pagarme/issues/124
=> popover-content: refactor popover style

src/styles/popover/index.css, src/styles/popover/properties.css
Reverts pagarme/former-kit-skin-pagarme#123
=> Revert "popover-content: refactor popover style"

src/styles/landing/index.css, src/styles/landing/properties.css
This PR changes the landing base styles according to our new Account page layout.
- Helps https://github.com/pagarme/pilot/pull/922
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5b0da1b13f3869780adab964
https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/5afb532cdc459a5251b87557
=> landing: refactor base

src/styles/flexbox/index.css, src/styles/index.js
Add styles to `Box` component.
related with pagarme/former-kit#146
=> flexbox: add component styles

src/styles/button/index.css, src/styles/button/properties.css
This PR add ripple effect with css only.
checkout to this branch and run `yarn build` in former-kit run `yarn storybook`
=> button: add ripple effect to button

package.json
=> chore: update former-kit version to 0.10.0

src/styles/input/index.css, src/styles/input/properties.css
This PR add `size` prop to `Input` component.
=> input: add prop size

src/styles/card/properties.css, src/styles/input/properties.css
Update spacing between items and input's placeholder color. Depends on https://github.com/pagarme/pilot/pull/1003
=> Cards: update spacing and input placeholder color

src/styles/spacing/index.css
I add `min-width: --spacing-tiny` in `flex` prop on Spacing component. Related to https://github.com/pagarme/pilot/pull/1003
=> spacing: update flex min-width

src/styles/avatar/index.css, src/styles/tag/index.css
It resolves the errors that are happening in the Pilot storybook terminal (max-empty-lines).
=> chore: refactor lint errors

package.json
This pull request bumps version from 0.10.0  to 0.11.0
=> update version to 0.11.0

package.json
Update to version 1.0 with major updates and fixes related to the update
=> Update to version 1.0

src/styles/sidebar/index.css, src/styles/sidebar/properties.css, src/styles/sidebar/sidebar-link.css
This is part of Sidebar's MicroInteration https://github.com/pagarme/pilot/issues/854 .
=> sidebar: add transition

src/styles/index.js, src/styles/snackbar/index.css, src/styles/snackbar/properties.css
This PR add the style for the `Snackbar` component: https://github.com/pagarme/former-kit/issues/167
* The creation of this component was made under the necessity of this kind of component to be use in this page: https://github.com/pagarme/former-kit/issues/167
=> snackbar: add style

src/styles/date-selector/index.css, src/styles/date-selector/properties.css, src/styles/z-index.css
The Sidebar component was separated from DateSelector and now we need a style for it. There was also needed some fixes for the Popover.
Dependency of https://github.com/pagarme/former-kit/pull/228
=> DateSelector: Aside and Popover Styles

package.json, yarn.lock
this pull request:
- add `react` and `react-dom` as dev dependencies
- update package to version `1.1.0`
=> update version to 1.1.0

package.json
this release includes:
- sidebar: refactor sidebar min-width #169
- button: add spinner loader #170
resolves #171
=> release  1.2.0

package.json, src/styles/index.js, src/styles/truncate/index.css
=> truncate: add style component

package.json
This release includes:
- card: remove title's white-space #174
resolves #175
=> release 1.3.1

package.json
this release includes:
- Fix Sidebar bugs #177
resolves #178
=> release 1.3.2

package.json
this release includes:
- Add style to control Modal width #181
resolves #187 187
=> release 1.3.3

package.json
=> bump version to  1.3.5

package.json
This release includes:
-  Segmented Switch new font size #197 
-  Fix Rubik font-weight and add new color #206 
- spaced-seg-switch: refactor font-size #205
- font: refactor font-weight and add new color #207
resolves #209
=> chore: bump version to 1.5.1

package.json
This release includes:
-  modal-actions: refactor margin-left in first-child #211
- modal-actions: refactor margin-left in first-child #211
resolves #212
=> chore: bump version to 1.5.2

package.json
This release fixes empty column alignment in Table component
=> release 1.5.3

package.json
This relase includes:
- Legend: add acronym text format class
- Header: change title font soze to 16px
- Card: change title color to `--color-light-coal-100`
- SegmentedSwitch: change padding to 8px
resolves #221
=> release 1.5.4

package.json
This release includes:
- Add roboto fonts.
- Add UIProgressBar alternative styles
resolves #224
=> release 1.6.0

package.json
This release adds:
- new color palette #226
- Modal: mobile size #229
resolves #230
=> release 1.7.0

src/icons/form-fields/secondary-dropdown/index.js, src/icons/index.js, src/styles/form-fields/secondary-dropdown/index.css, src/styles/form-fields/secondary-dropdown/properties.css, src/styles/index.js
This PR add the new dropdown variant that is required for the Onboarding history (https://github.com/pagarme/credenciamento/issues/471 and https://github.com/pagarme/pilot/issues/1579).
=> dropdown: add SecondaryDropdown

package.json
This release adds:
- SecondaryButton #228
- SecondaryDropdown #233
- Bump acorn related dependencies #232
=> chore: bump version to 1.8.0

src/styles/bullet-steps/properties.css, src/styles/dropdown/index.css, src/styles/dropdown/properties.css, src/styles/modal/index.css, src/styles/modal/properties.css
Este PR realiza as seguintes alterações:
- Adiciona o tamanho de modal pequeno
- Atualiza o estilo do bullet steps
- Atualiza o estilo padrão do dropdown
=> Add small modal

package.json, src/styles/dropdown/index.css
This release adds:
Ajuste no Dropdown default https://github.com/pagarme/former-kit-skin-pagarme/pull/238
=> Release 2.1.1

package.json, src/styles/sidebar/index.css, src/styles/sidebar/properties.css
Atualiza a posição do sidebar para ter mais maleabilidade de seus filhos.
=> CRED-13 chore: update sidebar position

src/icons/input/index.js, src/styles/button/index.css, src/styles/button/properties.css, src/styles/input/index.css, src/styles/input/properties.css
Issue relacionada: https://mundipagg.atlassian.net/browse/CRED-168
=> CRED-168: Redesign updates

package.json, src/styles/button/index.css, src/styles/button/properties.css
Seta o primeiro caracter do botão para ser maiusculo.
=> button: update set first letter uppercase

package.json, src/styles/alert/index.css
[CRED-257](https://mundipagg.atlassian.net/browse/CRED-257)
=> alert: update style

package.json, src/styles/alert/index.css
[CRED-187](https://mundipagg.atlassian.net/browse/CRED-187)
=> login: add custom alert

package.json, src/styles/popover/index.css, src/styles/popover/properties.css
Este Pr adiciona novo estilo para o popover
- Baixar essa branch  e o `former-kit` na mesma branch
- Instruções nesse pr [pr](https://github.com/pagarme/former-kit/pull/347)
=> chore: set new style to popover

package.json, src/styles/card/index.css, src/styles/card/properties.css, src/styles/tab-bar/index.css
**Contexto**
- Adiciona a opção de alinhar o Tab.
- Adiciona a opção de configurar o tamanho da fonte do cardTitle
=> Ajustes no CardTitle e Tab

package.json, src/styles/card/index.css, src/styles/card/properties.css
=> chore: update card fonts

package.json, src/styles/date-input/properties.css, src/styles/table/footer.css
=> Corrige imports de estilo

package.json, src/styles/sidebar/index.css
Em resoluções menores o menu lateral da pilot não é gerado o scroll, assim "cortando" todas as opções geradas. Esse PR tem o objetivo de corrigir este problema
- Utilize o comando `npm link` na Pilot e veja se é criado um scroll na resolução 1360x600
=> [EXP-821] Corrrige scroll no Menu Lateral na Pilot

package.json, src/styles/button/index.css, src/styles/button/properties.css
Estratégia para componentizar botão sem padding
- [Estratégia para componentizar botão sem padding](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=185&projectKey=EXP&modal=detail&selectedIssue=EXP-879)
**Preview com former-kit-skin-pagarme:**
=> [EXP-879] Componentizar botão sem padding

package.json, src/styles/color-picker/index.css, src/styles/color-picker/properties.css, src/styles/index.js
=> [EXP-998] Style Color picker

package.json, src/styles/sidebar/sidebar-link.css
adicionar style submenu de recorrência na sidebar
=> [EXP-1100] Adicionar style submenu de recorrência na sidebar

package-lock.json, package.json, src/styles/index.js, src/styles/popover-checkbox-group/index.css
- Novo componente de checkboxes que é aberto através de um popover.
- [ \[EXP-1160\] Componente PopoverCheckBox](https://mundipagg.atlassian.net/jira/software/c/projects/EXP/boards/185?modal=detail&selectedIssue=EXP-1160)
=> [EXP-1160] PopoverCheckboxGroup

README.md, package.json, src/styles/sidebar/properties.css, src/styles/sidebar/sidebar-link.css
Aumentar o espaco do click do botao no submenu
- Rodar `yarn build ` e `npm link`
- Acessar o former kit na branch `feat/add-items-menu` e rodar  `npm link former-kit-skin-pagarme ` 
- Rodar storybook e acessar o componente sidebar e validar se o click dos menu e submenu estao corretos
=> [EXP-1336] Aumentar o espaco do click do botao no submenu

package.json, src/styles/sidebar/properties.css, src/styles/sidebar/sidebar-link.css
Remover a borda quando o link esta ativo
Remover a borda quando o link esta ativo
=> Remover a borda quando o link esta ativo

package.json, src/styles/sidebar/index.css, src/styles/sidebar/properties.css, src/styles/sidebar/sidebar-header.css
Fazer com que o header do menu seja fixo
=> [EXP-1335] make the menu header fixed

package.json, src/styles/sidebar/properties.css, src/styles/sidebar/sidebar-link.css
Fixs menu
- Linkar com o former kit e verificar componenete sidebar
=> [EXP-1382] Fixs menu

src/styles/date-selector/index.css, src/styles/date-selector/properties.css, src/styles/popover/index.css, src/styles/popover/properties.css, src/styles/react-dates/index.css, src/styles/react-dates/properties.css
Visualmente a apresentação do filtro de datas apresenta distinções do que temos no former-kit para o que foi apresentado no FIGMA da nova funcionalidade do SEARCH, vamos modificar todos os elementos visuais do componente atual para ele ter maior fidelidade com o novo componente.
[Figma](https://www.figma.com/file/BBQcxO1U37PwqQjwDq7Ybl/Estudo-Novo-Filtro?type=design&node-id=2016-40527&t=3LfVQVIbo5aZtBmi-0)
- [MCFIN-193](https://mundipagg.atlassian.net/browse/MCFIN-193)
[MCFIN-193]: https://mundipagg.atlassian.net/browse/MCFIN-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MCFIN-193] [/SEARCH] Ajustar date-select do former-kit

src/styles/popover/properties.css, src/styles/react-dates/properties.css
Update style to propover component variables
- [Figma](https://www.figma.com/file/BBQcxO1U37PwqQjwDq7Ybl/Estudo-Novo-Filtro?type=design&node-id=2016-40528&t=cQto20Y5a1lymN8L-0)
- [Task MCFIN-190](https://mundipagg.atlassian.net/jira/software/c/projects/MCFIN/boards/854?modal=detail&selectedIssue=MCFIN-190)
=> [/SEARCH - MCFIN-190] Ajustar popover do former-kit

package.json, src/styles/button/properties.css, src/styles/date-selector/index.css, src/styles/date-selector/properties.css, src/styles/popover/index.css, src/styles/popover/properties.css, src/styles/react-dates/index.css, src/styles/react-dates/properties.css
Ajustes de layout para a demanda de Filtros.
- [MCFIN-190](https://mundipagg.atlassian.net/browse/MCFIN-190)
- [MCFIN-191](https://mundipagg.atlassian.net/browse/MCFIN-191)
- [MCFIN-193](https://mundipagg.atlassian.net/browse/MCFIN-193)
[MCFIN-190]: https://mundipagg.atlassian.net/browse/MCFIN-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MCFIN-191]: https://mundipagg.atlassian.net/browse/MCFIN-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MCFIN-193]: https://mundipagg.atlassian.net/browse/MCFIN-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release v2.16.0
