src/styles/typography.css
This PR adds a `sans-serif` fallback on both `title-font-family` and `body-font-family` properties.
=> typography: add sans-serif fallback

src/styles/grid/index.css
This fixes a small issue which could have a great impact on layouts
depending on `Grid` component.
We missed the `flex-direction: column` in `Col` styles, causing any `div`
placed as children of `Col` to be rendered in "column" direction
(effectively rendering as `div`s had `display: inline`)/
=> grid: fix col to have correct flex-direction

src/styles/spacing/index.css
`Spacing` is breaking line 
This PR adds `display: inline-flex` to fix line breakings
=> spacing: add display inline-flex

src/styles/popover/index.css, src/styles/popover/properties.css
This PR refactor Popover component
- Remove padding from `children`
- Remove text-transform uppercase from links on PopoverMenu
- Resolves https://github.com/pagarme/pilot/issues/762
=> popover: remove padding and uppercase text

src/styles/card/index.css
- Remove `overflow: hidden`
- Resolves https://github.com/pagarme/former-kit/issues/150
=> card: remove overflow hidden

src/styles/popover/index.css, src/styles/popover/properties.css
- fix z-index value.
- remove background gradient on base dark.
- remove border none from all selectors.
- add border none on first-child with base dark.
- add border-bottom only when first-child is not a only-child and `Popover` has no base dark.
- refactor `:before` values to `inherit`
- refactor `:hover`, `:focus` and `:active: states
resolve pagarme/pilot#762
=> popover: refactor styles

src/styles/sidebar/index.css, src/styles/sidebar/properties.css, src/styles/sidebar/sidebar-header.css, src/styles/sidebar/sidebar-link.css
- Remove `tv` media-query
- Change `titles` transform
- Add flex to the `nav`
- Refactor `titles` selectors
- Refactor menu icon to `Button` with icon
- Refactor `SidebarContent` padding
- Resolves https://github.com/pagarme/pilot/issues/751 & https://github.com/pagarme/pilot/issues/752
- It links with https://github.com/pagarme/former-kit/pull/157
=> sidebar: refactor style

src/icons/table/index.js, src/styles/table/head.css, src/styles/table/index.css, src/styles/table/properties.css
- Refactor background-color
- Refactor border-color
- Refactor `head` height
- Refactor `descending` and `ascending` icons
- Remove active `th` green line
- Add text-overflow to `item`
- Solves part of https://github.com/pagarme/pilot/issues/742
The issue https://github.com/pagarme/former-kit/issues/176 was created to complement this one because we had some problems with truncate items in columns and child tooltips using only css.
=> table: refactor style

src/styles/alert/index.css, src/styles/alert/properties.css
Refactor `Alert` component to use the Dark base.
=> alert: add base dark

src/styles/form-fields/input/index.css, src/styles/form-fields/properties.css, src/styles/input/index.css, src/styles/input/properties.css
Refactor `Input` component to use the Dark base.
=> input: add base dark

src/styles/modal/index.css, src/styles/modal/properties.css
Fixes modal vertical alignment by removing `transformY` usage and using overlay's `align-items` instead.
=> Modal - Fix vertical alignment

src/styles/flexbox/index.css
In **Pilot** project I found an error using flexbox, the container don't ocuppy all width size because the parent container has flexbox too, so to fix this I added a width with 100% in the style for flexbox container.
=> flexbox: fix container width

src/styles/popover/index.css, src/styles/popover/properties.css
This PR removes the `transform: translate` from middle and center type popovers to use transform to animate them.
- Helps https://github.com/pagarme/pilot/issues/856
=> popover: refactor alignment

src/styles/tooltip/index.css
This PR removes the `transform: translate` from middle and center type tooltips to use transform to animate them.
- Helps https://github.com/pagarme/pilot/issues/856
=> tooltip: refactor alignment

src/styles/card/properties.css, src/styles/grid/properties.css, src/styles/layout/properties.css
Grid refactor to solve space problem between cards and inside cards.
=> grid: refactor spacing

src/styles/modal/index.css, src/styles/modal/properties.css
Add transition to Modal. This PR is related to https://github.com/pagarme/pilot/pull/1014 and https://github.com/pagarme/former-kit/pull/204.
- Go to `add/modal-transition` branch in all repositories
```
git checkout add/modal-transition
```
- Create a link to former-kit-skin e former-kit repositories
```
yarn link
```
- Link former-kit-skin-pagarme
```
yarn link former-kit
```
- Link former-kit-skin-pagarme inside Pilot
```
yarn link former-kit
yarn link former-kit-skin
```
- Run normally storybook at former-kit/Pilot
```
yarn storybook
```
=> Modal: add transition

README.md, doc/how-to-install.md
Add the doc explaining how to install the former-kit-skin-pagarme. It is a **very simple** suggestion and needs more works to merge.
I know that the ideal would be don't need a manual explaining how to install, but it will need much more time to resolve, and we already need a doc about it.
=> doc: add how-to-install section

src/styles/sidebar/index.css, src/styles/sidebar/properties.css
After Microinteration's Sidebar merge, notice that the lower the resolution, the Sidebar breaks being "squeezed" as the page resolution gets smaller until gets invisible to the user.
- Go to `fix/sidebar-min-width` branch
- Generate an .tgz file from `former-kit-skin-pagarme` repository
- Copy this file and paste in `pilot` repository
- Change the package `"former-kit-skin-pagarme": "1.1.0"` to `  "former-kit-skin-pagarme": "../../former-kit-skin-pagarme-1.1.0.tgz"`
- Delete `node_modules/` and `dist/` from `pilot/`
- Run `yarn` in `pilot` repository
- Go to `packages/pilot` and run `yarn start` :tada:
=> sidebar: refactor sidebar min-width

src/styles/button/index.css
Currently the button component does not have a way to handle actions trigger loadings, this PR adds the style to the loader in the spinner format.
1. Checkout to this branch.
2. Make sure this branch was linked with former-kit/add/button-loader.
3. In FormerKit run storybook.
=> button: add spinner loader

src/styles/card/index.css
In `release/v0.15.0` we have an bug on the CardTitle component of the Card presented in Dash, which makes Percy always alert.
- Go to `refactor/card-white-space` branch
- Generate an link from this repo with `yarn link`
- Go to `release/v0.15.0` of Pilot's repository
- Link this repository to Pilot with `yarn link former-kit-skin-pagarme`
- Run Pilot normally and check with this white-space persists in Card titles. :tada:
=> card: remove title's white-space

src/styles/sidebar/index.css, src/styles/sidebar/properties.css, src/styles/tooltip/index.css, src/styles/tooltip/properties.css, src/styles/z-index.css
This PR fixes the features displayed in the sidebar when it is collapsed. And, there's a fix on the Sidebar tooltips (which were not showing up).
Depends on https://github.com/pagarme/former-kit/pull/266 and https://github.com/pagarme/pilot/pull/1244
=> Fix Sidebar bugs

src/styles/modal/index.css, src/styles/modal/properties.css
This PR add the style for the `Modal` component: https://github.com/pagarme/former-kit/issues/231
* The necessity of this component was made under this problem: 
The implematation of these changes is going to happen here: https://github.com/pagarme/caesar/issues/358
=> modal: add styles

src/styles/segmented-switch/properties.css, src/styles/segmented-switch/spaced/index.css
We need to add the stylings for the new props `relevance` and `spacing` implemented on `SpacedSegmentedSwitch`
1. Link to `former-kit/add/low-relevance-segmentedswitch`
2. Run former-kit's storybook
=> SegmentedSwitch - Add styling for low relevance and tiny spacing

src/styles/colors/light.css, src/styles/sidebar/properties.css
This PR updates sidebar header's padding and adds a new color into `colors.css`.
- Go to branch `update/menu-icons` 
- Update your local dependencies with `yarn`
- Generate a link with `yarn link`
- Use this link in `pilot` repository with `yarn link former-kit-skin-pagarme`
- Check if all the updates are there. That's it! :tada:
=> Update Sidebar Header padding + add new color

package.json, yarn.lock
bump emblematic-icons to 0.7.1
bump react-dates to 18.4.1
bump react to 16.9.0
bump react-dom to 16.9.0
1. checkout branch `chore/bump-react`
2. install dependencies `yarn`
3. crate a link `yarn link`
4. navigate to former-kit and checkout `former-kit` master branch
5. link `former-kit-skin-pagarme` with `former-kit` `yarn link former-kit-skin-pagarme`
6. run `yarn`
7. run storybook `yarn storybook`
related #200
=> bump react related dependencies

src/styles/segmented-switch/properties.css
This PR changes font-size of spaced segment switch. 
- Generate the link of former-kit-skin-pagarme.
- Link the former-kit-skin-pagarme with the former-kit. Go to former-kit repository and run ``yarn link former-kit-skin-pagarme``.
- Run ``yarn storybook``.
- Go to spacedsegmentedswitch and check if the font-size is 12px.
=> spaced-seg-switch: refactor font-size

src/styles/colors/light.css, src/styles/webfonts/rubik/index.css
Font-weight was not being respected through the words ``lighter, normal and bold``.
Changed the values ​​to numeric ranges.
In order to acomplish our new design necessities for `BalanceTotalDisplay` component, we need to add the new color `#4d4f62`.
This PR does that, naming it  `--color-light-noir-100`.
=> font: refactor font-weight and add new color

src/styles/modal/index.css
`ModalActions` component adds margin even on it's first button, a behavior that is unexpected considering the idea is to add space *between* each button. This causes the buttons to not be correctly aligned.
This PR solves that.
**Checklist**
- Generate the link of former-kit-skin-pagarme.
- Link the former-kit-skin-pagarme with the former-kit. Go to former-kit repository and run ``yarn link former-kit-skin-pagarme``
- Run ``yarn storybook``
- Go to `Modal/ Default` 
- Open the modal and check if the first button have margin-left.
=> modal-actions: refactor margin-left in first-child

src/styles/table/body.css
This PR fixes the alignment from the tableEmptyItem span. Bug found in Pilot's `release/v0.21.0`.
- Generate an link `former-kit-skin-pagarme`  with `yarn link` and go to `pilot` repository locally and `yarn link former-kit-skin-pagarme`
- See if tableEmptyItem in TransactionsList is with the correct alignment. :tada:
=> table: refactor tableEmptyItem style

src/styles/legend/index.css, src/styles/legend/properties.css
This PR add `capitalize` and `uppercase` classes to Legend component.
``
{
text-transform: capitalize;
}
``
``
{
text-transform: uppercase;
}
``
=> Legend: add format class

src/styles/card/properties.css, src/styles/header/properties.css, src/styles/segmented-switch/properties.css
After analysis in issue https://github.com/pagarme/pilot/issues/1468, we verified the need for visual adjustments, given the differences between what is coded and the values in layout.
Header
Card
SegmentedSwitch
=> Visual adjustments to components Header, Card and SegmentedSwitch

src/styles/colors/light.css
This PR add the new color palette that was created by @lucas-hidalgo. The palette can be found [here](https://www.figma.com/file/3GCJip7FTCcOAC1A4e2wGk/Colors).
For the onboarding screen that will be constructed (https://github.com/pagarme/pilot/issues/1579) we need this new colors as variables.
=> Add new color palette

src/styles/modal/index.css, src/styles/modal/properties.css
Precisamos do modal compativel com tamanho mobile para uso no linkApp.
- no `former-kit-skin` entre na branch `add/modal-mobile-size`
- rode `yarn link`
- no `former-kit` entre na branch `add/modal-mobile-size` 
- rode `yarn link "former-kit-skin-pagarme"`
- rode `yarn storybook`
- cheque a historia do Modal com tamanho mobile
=> Adiciona tamanho mobile no componente Modal - skin

src/styles/button/default/index.css, src/styles/button/default/properties.css, src/styles/button/properties.css, src/styles/button/secondary-button/index.css, src/styles/button/secondary-button/properties.css, src/styles/index.js
This PR add the new button variant that is required for the Onboarding history (https://github.com/pagarme/credenciamento/issues/437 and https://github.com/pagarme/pilot/issues/1579).
This PR duplicate a part of the code from `UIButton`, but only the code required for meet the default button props requirements. My idea is that as we are migrating to a new variant, the code is duplicated from the previous version, but only the part of the code that was needed now, and as we need the others features (outline button, circle button, etc), we can implement they. This make senses? :thinking: :smile:
=> button: add secondary button variant

src/styles/dropdown/index.css
Este PR remove o `width: 100%` do Dropdown default. Este valor foi adicionado no commit https://github.com/pagarme/former-kit-skin-pagarme/pull/236/commits/648f8c7eed5876f95893b52d5abe094415486a9a, porem, este valor está impactando como este componente se comporta quando há outros componentes próximos.
Desta forma, este PR remove o valor para voltar a configuração antiga.
=> Ajuste no Dropdown default

README.md
The license link was broken in the README.md file.
=> chore: fix LICENSE link

src/styles/card/index.css
Removing the gray color in the background.
Before:
After:
=> fix: CardActions background color

package.json, src/styles/form-fields/input/index.css
Esse PR corrige a visualização de campo desabilitado que ocorre apenas no navegador Safari.
- Fazer o link dessa pacote buildado no projeto da Pilot
- Acessar a tela de "Dados cadastrais" no navegador Safari e os valores dos campos devem estar visiveis.
=> EXP-789 Campos com estado bloqueado estão com valores "transparentes" no Safari

package.json, src/styles/alert/index.css, src/styles/modal/index.css
Possibilitar scroll interna na modal e limitar a sua altura para não ocupar toda a tela do usuário. Alinhar os elementos de um alerta no seu centro.
- [[EXP-918] Possibilitar scroll interna na modal](https://mundipagg.atlassian.net/secure/RapidBoard.jspa?rapidView=185&projectKey=EXP&modal=detail&selectedIssue=EXP-918)
[EXP-918]: https://mundipagg.atlassian.net/browse/EXP-918
=> [EXP-918] Possibilitar scroll interna na modal

src/styles/button/properties.css
Atualmente possuimos um estilo de botão chamado “Low relevance”, que pode ser consultado [nesse link](https://pagarme.github.io/former-kit/storybook/?path=/story/buttons--default), que por muitas vezes os usuários entendem como um botão desabilitado e, devido a isso, acabam não clicando.
- [MCFIN-191](https://mundipagg.atlassian.net/browse/MCFIN-191)
[MCFIN-191]: https://mundipagg.atlassian.net/browse/MCFIN-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MCFIN-191][/SEARCH] Ajustar variação de botão do former-kit
